version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - npm ci

  build:
    commands:
      - echo "Node.js application build completed successfully!"
  
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - '.env'